### ISSUE TITLE
Two questions...

### ISSUE THREAD

**Issue by reintroducing** [EvandroLG/transitionEnd#7]
Hi, great little utility you have here.  I have two questions:

1) Can you list browser support in the readme? It's not immediately clear how far back the support goes in IE.  Some polyfills only support unifying the event but not older browsers.  What is the support for this one?

2) Is it possible to publish this on npm? Would love to use it and manage updates through our npm ecosystem setup in the project.

Thanks for your hard work on this!

**Comment by EvandroLG** [comment]
Hi man,

1) This library just supports the newer browsers. Anyway, I added the what's the current support 👍 
2) I just published it on npm! 👍 

Thanks

**Comment by reintroducing** [comment]
Awesome, thanks for that.

In regards to browser support, I was under the impression lower versions of IE were supported. According to https://github.com/EvandroLG/transitionEnd/issues/1 it sounds like he was using it in IE8. Is this not the case?

**Comment by EvandroLG** [comment]
Actually, it doesn't work in IE8 =/
The library just works in browsers that implements transitionEnd event in some way.

**Comment by reintroducing** [comment]
Sure, I'm actually looking for IE9 support, but im assuming then it doesn't support 9 either?
